### ISSUE TITLE
Integration with rviz panel - set initial estimate

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/atom#279]
Hi @MiguelDRPina ,

Please list all other functionalities we need to develop for the set_initial_estimate. I can remember the following:

- [x] hide / show interactive marker controls (#278)
- [x] change scale of controls
- [x] button to save and and reset sensor pose (#280)
- [x] micro movements of the control (#285)

**Comment by miguelriemoliveira** [comment]
New service created in 4c67a17f4e38dd155e608f4440d5c9a0efedc7df called SetSensorInteractiveMarker.srv

https://github.com/lardemua/atom/blob/noetic-devel/atom_msgs/srv/SetSensorInteractiveMarker.srv

It should support most of the listed functionalities. Changing scale is already working, just call the service above with different scale values.
