### ISSUE TITLE
Collect real data at INESC 2024 (zaubot)

### ISSUE THREAD

**Issue by miguelriemoliveira** [lardemua/atom#894]
Sensors:

- [x] #904
- [x] intel t265 (@brunofavs )(#909)
- [x] intel l515 (hand camera rgbd ) (@manuelgitgomes ) (#903)
- [x] astra (rgb only, front body camera) (@Kazadhum ) (#902)
- [x] astra (rgb only, rear body camera) (@Kazadhum ) (#902 )
- [x] Example (#901)

Create xacro of the zaubot.

Up to 5 of april . Sensors working separate.

Up to 12 of april. Sensors working all in a single laptop.

**Comment by miguelriemoliveira** [comment]
Hi all,

please create issues for each task above and add the number, like in the example above.

**Comment by Kazadhum** [comment]
Hello @manuelgitgomes and @brunofavs! I talked with @miguelriemoliveira and we had the idea of gathering on the 8th of April at LAR to try and get all the sensors working together.

Are you available?

**Comment by brunofavs** [comment]
Hey
The proposed date sounds good to me :)

**Comment by miguelriemoliveira** [comment]
Hello to all. Thank you for your efforts in making each sensor work separately. I think that milestone is almost complete. 
One thing we have to have tough, is the ability to change the resolution of the sensors (perhaps not the velodyne) and the data frequency (including the velodyne). 

Ideally each launch file for the sensor should have arguments where we can define these parameters.

I am saying this because I am anticipating a very large data throughput, which can be solved by reducing resolution and freqquency.

**Comment by brunofavs** [comment]
My pc lacks thunderbolt 4's huge usb bandwidths, only supporting usb 3.2 gen 1 which goes up to 10Gb/s I think.

Do you reckon it will be enough?

**Comment by miguelriemoliveira** [comment]
I think so. Because we're using the bagfile for calibration then we could use just 5 or 10 hz. If that is not enough we can reduce resolution of cameras

**Comment by manuelgitgomes** [comment]
Data collection done, closing this.
